name: Release Packages

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Update Mihomo Version]
    types: [completed]

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.release }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          #- arm_cortex-a5_vfpv4
          #- arm_cortex-a7_neon-vfpv4
          #- arm_cortex-a8_vfpv3
          #- arm_cortex-a9
          #- arm_cortex-a9_vfpv3-d16
          #- arm_cortex-a9_neon
          #- arm_cortex-a15_neon-vfpv4
          #- aarch64_cortex-a53
          #- aarch64_cortex-a72
          - aarch64_generic
          #- mips_24kc
          #- mips_4kec
          #- mips_mips32
          #- mipsel_24kc
          #- mipsel_24kc_24kf
          #- mipsel_74kc
          #- mipsel_mips32
          #- mips64_octeonplus
          #- i386_pentium4
          - x86_64
        release:
          - openwrt-23.05

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          FEEDNAME: mihomo
          PACKAGES: luci-app-mihomo
          NO_REFRESH_CHECK: true

      - name: Compress
        run: |
          tar -c -z -f mihomo_${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/mihomo .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.release }}
          path: bin/packages/${{ matrix.arch }}/mihomo/*.ipk
          
      - name: Delete previous release
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            if (releases.data.length > 0) {
              const latestRelease = releases.data[0];
              await github.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: latestRelease.id
              });
              await github.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${latestRelease.tag_name}`
              });
            }

      - name: Create new release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: $(date +'%Y-%m-%d')
          release_name: Release $(date +'%Y-%m-%d')
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/packages/${{ matrix.arch }}/mihomo/*.ipk
          asset_name: ${{ matrix.arch }}-${{ matrix.release }}.ipk
          asset_content_type: application/octet-stream